name: biggles-conda

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:

      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install system deps
        run: sudo apt install libx11-dev libxft-dev libxt-dev libxaw7-dev libpng-dev

      - name: Install special dependencies with conda and pip
        shell: bash -l {0}
        run:  conda install -q -y numpy pytest

      - name: Install code
        shell: bash -l {0}
        run: pip install --no-deps .

      - name: Run pytest
        shell: bash -l {0}
        run: pytest -vv tests
